// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppBibliotek.Data;

namespace WebAppBibliotek.Migrations
{
    [DbContext(typeof(WebAppDBContext))]
    [Migration("20220104141111_addTitleColumn")]
    partial class addTitleColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAppBibliotek.Models.Book", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("_author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("_price")
                        .HasColumnType("int");

                    b.Property<string>("_title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("_id");

                    b.ToTable("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
